---
- name: Power off host
  hosts: all  # Run the playbook locally to execute the gcloud command
  gather_facts: no  # We don't need facts about the target hosts

  tasks:
    - name: Confirm shutdown
      pause:
        prompt: "Are you sure you want to shut down the instance? (yes/no)"
      register: confirm_shutdown

    - name: Shut down the VM instance
      command: gcloud compute instances stop testing --zone europe-west4-a
      when: confirm_shutdown.user_input == 'yes'
