---
- name: Shutdown GCP Instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Shutdown GCP Instance
      command: gcloud compute instances stop testing --zone europe-west4-a
      args:
        executable: /bin/bash
      environment:
        CLOUDSDK_COMPUTE_ZONE: "europe-west4-a"
      become: yes
      become_user: bacem_hlabba
